-- MySQL Script generated by MySQL Workbench
-- Wed Dec 23 09:07:17 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_entel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_entel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_entel` DEFAULT CHARACTER SET utf8 ;
USE `db_entel` ;

-- -----------------------------------------------------
-- Table `db_entel`.`tecnologias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_entel`.`tecnologias` (
  `id_tecnologia` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_tecnologia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_entel`.`operadores_telefonicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_entel`.`operadores_telefonicos` (
  `id_operador_telefonico` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `codigo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_operador_telefonico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_entel`.`tecnologias_operadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_entel`.`tecnologias_operadores` (
  `id_tecnologia_operador` INT NOT NULL AUTO_INCREMENT,
  `id_tecnologia` INT NOT NULL,
  `id_operador_telefonico` INT NOT NULL,
  PRIMARY KEY (`id_tecnologia_operador`),
  INDEX `fk_tecnologia_operador_tecnologias1_idx` (`id_tecnologia` ASC),
  INDEX `fk_tecnologia_operador_operadores_telefonicos1_idx` (`id_operador_telefonico` ASC),
  CONSTRAINT `fk_tecnologia_operador_tecnologias1`
    FOREIGN KEY (`id_tecnologia`)
    REFERENCES `db_entel`.`tecnologias` (`id_tecnologia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tecnologia_operador_operadores_telefonicos1`
    FOREIGN KEY (`id_operador_telefonico`)
    REFERENCES `db_entel`.`operadores_telefonicos` (`id_operador_telefonico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_entel`.`sedes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_entel`.`sedes` (
  `id_sede` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_sede`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_entel`.`equipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_entel`.`equipos` (
  `id_equipo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `ip` VARCHAR(15) NOT NULL,
  `tipo` VARCHAR(100) NOT NULL,
  `ranuras` INT NOT NULL,
  `id_sede` INT NOT NULL,
  `estado` ENUM('A', 'D') NULL,
  PRIMARY KEY (`id_equipo`),
  INDEX `fk_equipos_ubicaciones1_idx` (`id_sede` ASC),
  CONSTRAINT `fk_equipos_ubicaciones1`
    FOREIGN KEY (`id_sede`)
    REFERENCES `db_entel`.`sedes` (`id_sede`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_entel`.`canales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_entel`.`canales` (
  `id_canal` INT NOT NULL AUTO_INCREMENT,
  `id_tecnologia_operador` INT NULL,
  `id_equipo` INT NOT NULL,
  `nombre` VARCHAR(100) NULL,
  `estado` ENUM('A', 'I') NULL,
  `nro_ranura` INT NOT NULL,
  `numero` VARCHAR(10) NULL,
  PRIMARY KEY (`id_canal`),
  INDEX `fk_canales_tecnologia_operador1_idx` (`id_tecnologia_operador` ASC),
  INDEX `fk_canales_equipos1_idx` (`id_equipo` ASC),
  CONSTRAINT `fk_canales_tecnologia_operador1`
    FOREIGN KEY (`id_tecnologia_operador`)
    REFERENCES `db_entel`.`tecnologias_operadores` (`id_tecnologia_operador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_canales_equipos1`
    FOREIGN KEY (`id_equipo`)
    REFERENCES `db_entel`.`equipos` (`id_equipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_entel`.`numeros_externos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_entel`.`numeros_externos` (
  `id_numero_externo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `comentario` TEXT NOT NULL,
  `numero` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_numero_externo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_entel`.`matrices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_entel`.`matrices` (
  `id_matriz` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_matriz`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_entel`.`perfiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_entel`.`perfiles` (
  `id_perfil` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `estado` ENUM('A', 'D') NOT NULL,
  PRIMARY KEY (`id_perfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_entel`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_entel`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(150) NOT NULL,
  `apellidos` VARCHAR(150) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `acceso` ENUM('A', 'D') NOT NULL,
  `clave` VARCHAR(150) NOT NULL,
  `id_perfil` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_usuarios_perfiles1_idx` (`id_perfil` ASC),
  CONSTRAINT `fk_usuarios_perfiles1`
    FOREIGN KEY (`id_perfil`)
    REFERENCES `db_entel`.`perfiles` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_entel`.`pruebas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_entel`.`pruebas` (
  `id_prueba` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `comentario` TEXT NOT NULL,
  `correo` VARCHAR(150) NOT NULL,
  `tiempo_timbrado` INT NOT NULL,
  `reintentos` INT NOT NULL,
  `tipo_lanzamiento` VARCHAR(70) NOT NULL,
  `programacion` VARCHAR(1) NULL,
  `ejecutado` VARCHAR(2) NULL,
  `fecha_lanzamiento` DATE NULL,
  `hora_lanzamiento` TIME NULL,
  `dias_lanzamiento` VARCHAR(45) NULL,
  `id_matriz` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_prueba`),
  INDEX `fk_pruebas_matrices1_idx` (`id_matriz` ASC),
  INDEX `fk_pruebas_usuarios1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_pruebas_matrices1`
    FOREIGN KEY (`id_matriz`)
    REFERENCES `db_entel`.`matrices` (`id_matriz`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pruebas_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db_entel`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_entel`.`modulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_entel`.`modulos` (
  `id_modulo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  `ruta` VARCHAR(50) NOT NULL,
  `icono` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_modulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_entel`.`submodulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_entel`.`submodulos` (
  `id_submodulo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  `ruta` VARCHAR(50) NOT NULL,
  `icono` VARCHAR(50) NOT NULL,
  `id_modulo` INT NOT NULL,
  PRIMARY KEY (`id_submodulo`),
  INDEX `fk_submodulos_modulos1_idx` (`id_modulo` ASC),
  CONSTRAINT `fk_submodulos_modulos1`
    FOREIGN KEY (`id_modulo`)
    REFERENCES `db_entel`.`modulos` (`id_modulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_entel`.`perfiles_submodulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_entel`.`perfiles_submodulos` (
  `id_perfil` INT NOT NULL,
  `id_submodulo` INT NOT NULL,
  INDEX `fk_perfiles_modulos_perfiles1_idx` (`id_perfil` ASC),
  INDEX `fk_perfiles_modulos_submodulos1_idx` (`id_submodulo` ASC),
  CONSTRAINT `fk_perfiles_modulos_perfiles1`
    FOREIGN KEY (`id_perfil`)
    REFERENCES `db_entel`.`perfiles` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_perfiles_modulos_submodulos1`
    FOREIGN KEY (`id_submodulo`)
    REFERENCES `db_entel`.`submodulos` (`id_submodulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_entel`.`credenciales_api`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_entel`.`credenciales_api` (
  `id_credencial_api` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  `estado` ENUM('A', 'D') NOT NULL,
  PRIMARY KEY (`id_credencial_api`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_entel`.`errores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_entel`.`errores` (
  `id_error` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(50) NULL,
  `estado` VARCHAR(100) NULL,
  `mensaje` TEXT NULL,
  PRIMARY KEY (`id_error`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_entel`.`ejecuciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_entel`.`ejecuciones` (
  `id_ejecucion` INT NOT NULL AUTO_INCREMENT,
  `fecha_inicio` DATETIME NOT NULL,
  `fecha_fin` DATETIME NULL,
  `estado` TEXT NOT NULL,
  `id_matriz` INT NOT NULL,
  PRIMARY KEY (`id_ejecucion`),
  INDEX `fk_ejecucion_matrices1_idx` (`id_matriz` ASC),
  CONSTRAINT `fk_ejecucion_matrices1`
    FOREIGN KEY (`id_matriz`)
    REFERENCES `db_entel`.`matrices` (`id_matriz`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_entel`.`escenarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_entel`.`escenarios` (
  `id_escenario` INT NOT NULL AUTO_INCREMENT,
  `id_ejecucion` INT NOT NULL,
  `id_canal_origen` INT NOT NULL,
  `id_destino` INT NOT NULL,
  `tipo` ENUM('C', 'E') NOT NULL,
  `uniqueid_en` VARCHAR(200) NOT NULL,
  `uniqueid_sal` VARCHAR(200) NOT NULL,
  `estado` TEXT NOT NULL,
  `id_error` INT NULL,
  PRIMARY KEY (`id_escenario`),
  INDEX `fk_escenarios_canales1_idx` (`id_canal_origen` ASC),
  INDEX `fk_escenarios_ejecucion1_idx` (`id_ejecucion` ASC),
  INDEX `fk_escenarios_error1_idx` (`id_error` ASC),
  CONSTRAINT `fk_escenarios_canales1`
    FOREIGN KEY (`id_canal_origen`)
    REFERENCES `db_entel`.`canales` (`id_canal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_escenarios_ejecucion1`
    FOREIGN KEY (`id_ejecucion`)
    REFERENCES `db_entel`.`ejecuciones` (`id_ejecucion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_escenarios_error1`
    FOREIGN KEY (`id_error`)
    REFERENCES `db_entel`.`errores` (`id_error`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_entel`.`matrices_canales_destinos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_entel`.`matrices_canales_destinos` (
  `id_matriz_canal_destino` INT NOT NULL AUTO_INCREMENT,
  `id_matriz` INT NOT NULL,
  `id_canal_origen` INT NOT NULL,
  `id_destino` INT NOT NULL,
  `tipo` ENUM('C', 'E') NOT NULL,
  PRIMARY KEY (`id_matriz_canal_destino`),
  INDEX `fk_escenarios_matrices1_idx` (`id_matriz` ASC),
  INDEX `fk_escenarios_canales1_idx` (`id_canal_origen` ASC),
  CONSTRAINT `fk_escenarios_matrices10`
    FOREIGN KEY (`id_matriz`)
    REFERENCES `db_entel`.`matrices` (`id_matriz`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_escenarios_canales10`
    FOREIGN KEY (`id_canal_origen`)
    REFERENCES `db_entel`.`canales` (`id_canal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
